export const GENRE_TRANSLATIONS: Record<string, string> = {
  'Action': 'Hành động',
  'Adventure': 'Phiêu lưu',
  'Animation': 'Hoạt hình',
  'Comedy': 'Hài',
  'Crime': 'Tội phạm',
  'Documentary': 'Tài liệu',
  'Drama': 'Chính kịch',
  'Family': 'Gia đình',
  'Fantasy': 'Phiêu lưu kỳ thú',
  'History': 'Lịch sử',
  'Horror': 'Kinh dị',
  'Music': 'Âm nhạc',
  'Mystery': 'Bí ẩn',
  'Romance': 'Lãng mạn',
  'Science Fiction': 'Khoa học viễn tưởng',
  'TV Movie': 'Phim truyền hình',
  'Thriller': 'Gay cấn',
  'War': 'Chiến tranh',
  'Western': 'Miền Tây',
  'Sci-Fi & Fantasy': 'Khoa học viễn tưởng',
  'Action & Adventure': 'Hành động & Phiêu lưu',
  'War & Politics': 'Chiến tranh & Chính trị',
  'Soap': 'Phim dài tập',
  'Talk': 'Talk show',
  'News': 'Tin tức',
  'Reality': 'Thực tế',
  'Kids': 'Thiếu nhi'
};
